Ray cluster started. Available resources: {'node:__internal_head__': 1.0, 'node:172.23.48.184': 1.0, 'accelerator_type:G': 1.0, 'object_store_memory': 4101873254.0, 'GPU': 1.0, 'CPU': 12.0, 'memory': 9571037594.0}
Waiting for actors to initialize and run one episode...
[36m(LearnerActor pid=28065)[0m (Learner pid=28065) Initializing on GPU...
[36m(LearnerActor pid=28065)[0m (Learner pid=28065) Setup complete.
[36m(DataActor pid=28074)[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): [36mray::ReplayBufferActor.add()[39m (pid=28063, ip=172.23.48.184, actor_id=5160412da20441fb69834c6501000000, repr=<train.ReplayBufferActor object at 0x78714dbea650>)
[36m(DataActor pid=28074)[0m   File "/home/ryan/toy_mazero/train.py", line 45, in add
[36m(DataActor pid=28074)[0m     self.replay_buffer.add(item, priority)
[36m(DataActor pid=28074)[0m   File "/home/ryan/toy_mazero/utils/replay_buffer.py", line 126, in add
[36m(DataActor pid=28074)[0m     self.actions[self.pointer] = item.actions
[36m(DataActor pid=28074)[0m ValueError: could not broadcast input array from shape (5,3) into shape (5,5)

Warmup phase...
  Buffer size: 0/1000
[36m(DataActor pid=28073)[0m [32m2025-06-29 16:38:11[0m | [36mDEBUG[0m | [36mUpdating parameters from learner.[0m
Traceback (most recent call last):
  File "/home/ryan/toy_mazero/train.py", line 466, in <module>
    main()
  File "/home/ryan/toy_mazero/train.py", line 400, in main
    done_refs, _ = ray.wait(list(actor_tasks.keys()), num_returns=1)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 3080, in wait
    ready_ids, remaining_ids = worker.core_worker.wait(
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ryan/toy_mazero/train.py", line 466, in <module>
    main()
  File "/home/ryan/toy_mazero/train.py", line 400, in main
    done_refs, _ = ray.wait(list(actor_tasks.keys()), num_returns=1)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 3080, in wait
    ready_ids, remaining_ids = worker.core_worker.wait(
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x70887455da20>
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 90, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 218, in teardown
    self._router.join()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
Exception ignored in atexit callback: <function shutdown at 0x7088962dd630>
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/ryan/miniconda3/envs/jaxmarl_env/lib/python3.10/site-packages/ray/_private/worker.py", line 1986, in shutdown
    time.sleep(0.5)
KeyboardInterrupt:
